---
ruby_executable: "/usr/bin/ruby2.5"
gems_install_path: /home/esrocos/.autoproj/gems"
prefer_indep_over_os_packages: false
osdeps_mode: all
reused_autoproj_installations: []
manifest_source:
  type: git
  url: https://github.com/ESROCOS/buildconf.git
  push_to: https://github.com/ESROCOS/buildconf.git
  branch: next-release
GITHUB: http,http
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: 'git@github.com:'
GITHUB_PRIVATE_ROOT: 'git@github.com:'
operating_system:
- - debian
- - '9'
  - stretch
  - default
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
cxx11: true
typelib_cxx_loader: castxml
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
SPASSGIT: http,http
SPASSGIT_ROOT: https://spass-git-ext.gmv.com
SPASSGIT_PUSH_ROOT: 'git@spass-git-ext.gmv.com:'
SPASSGIT_PRIVATE_ROOT: 'git@spass-git-ext.gmv.com:'
